# Generated by Django 2.0.3 on 2018-03-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zdanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdanie_zdanie', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='slowo',
            name='slowo_zdanie',
        ),
        migrations.AddField(
            model_name='zdanie',
            name='zdanie_slowo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dic.Slowo'),
        ),
    ]
